### ISSUE TITLE
Would this work with Live sources ? 

### ISSUE THREAD

**Issue by Svyatk0** [jb-alvarado/ffplayout#1]
Hey, quick question. 

Wonder whether this tool would work with a mixture of VOD and Live ? 

Cheers

Svyatko

**Comment by jb-alvarado** [comment]
Hi, 
theoretical it can work with everything what ffmpeg can handle. The problem I see, is how ffplayout will know when your live sources starts and when it ends. When you give it a fixed time in the playlist, it should work.

In my TODO list I have a live injection feature, but I don't know when and if I will integrated it.

**Comment by zeilsteen2** [comment]
Great work on the playout!  It rolling fine with files.

I tried the live option with udp and hls streams but it is not picking that up if I put the url in the playlist. Do you have any more hints for getting that live ingest working?

**Comment by jb-alvarado** [comment]
Can it be, that you have special characters in the address? xml for example don't like ampersand (&). Maybe this is the reason?

For integrating real life injecting if have no time at the moment. Is not so easy, because it needs a something like a "webserver" to listen on the port and forward the traffic.

**Comment by zeilsteen2** [comment]
Hello, 

I got the live ingest working by disabling the path/file check and I will try an ffprobe there for the stream. But it does play livestreams from the playlist. You just have to make an xml change for it in some way to start it like you said. I have not been able to stop the stream once it started. I installed the rtmp streamserver from here:

https://obsproject.com/forum/resources/how-to-set-up-your-own-private-rtmp-server-using-nginx.50/

And use a stream on that server as a source. 

rtmp://192.168.2.2/live/test2

greatings

**Comment by zeilsteen2** [comment]
Ok, I have now.

If you make a fifo:

mkfifo /tmp/test.mp4  and run:
ffmpeg -i rtmp://localhost/live/test2 -c copy -f mpegts /tmp/test.mp4

You can play and stop the stream with the file check enabled because the livestream becomes a file on the server.

**Comment by jb-alvarado** [comment]
Hi zeilsteen2,
nice that you got it to work! And yes you are right, now it comes to my mind - ffplayout checks every file if it exist, but of course streams can not be checked :).

We can integrate a ignore list for protocols and check if the input is in this list. Have you try with an normal ffmpeg command to stop the stream? Like: 

```bash
ffmpeg -i  rtmp://stream -t 100 ...
``` 
Another issue I can think about is the realtime playback. ffmpeg can not read the live source faster, so in the worst case the program runs out of buffer.

**Comment by jb-alvarado** [comment]
In dev branch I'm working on a version where live sources now possible. Came you test this?

https://github.com/jb-alvarado/ffplayout/tree/dev

**Comment by jb-alvarado** [comment]
Short before closing time is not good to publish :). The length from the live source is not correct, this needs a new calculation, because seek is not possible, so the diff should be the new length.

**Comment by zeilsteen2** [comment]
Great, I will try it. What is the best way to add the source in the xml playlist then?
I tried the original and got a playlist out of sync.

Thanks

Herman

**Comment by jb-alvarado** [comment]
Hello Herman,
in the next hour will come a small fix.

Normally there is no spacial way to add it in the playlist, only take care of this point from wiki:
https://github.com/jb-alvarado/ffplayout/wiki/Live-Source

**Comment by jb-alvarado** [comment]
I think the current version, commit 889a57bbdc66895bd5c00315c5d549b5223274f8 should work now!

**Comment by zeilsteen2** [comment]
Thank you for the update, I am trying it.

Don't know how to comment on the changes but in the sh playlistmaker there is a typo WC is wc.

When I try the copy mode I get an error for using double filtering in ffmpeg and also when I disable the filters in the compression config section.

Will try some more.

**Comment by jb-alvarado** [comment]
Thank you Herman, for pointing this out! I fixed both issues.
Maybe after the weekend I will merge the dev branch to master and make it official.

**Comment by jb-alvarado** [comment]
I think, I can close here. If something is not working, just open a new issue.
