### ISSUE TITLE
More then one out_addr option

### ISSUE THREAD

**Issue by Angel54689** [jb-alvarado/ffplayout#10]
Is it possible? More than one out_addr?

**Comment by Angel54689** [comment]
It's possible. Just need to add:

`out_addr_1 = rtmp://hls/address/key`

**Comment by jb-alvarado** [comment]
You can try to use the [tee muxer](https://www.ffmpeg.org/ffmpeg-formats.html#tee-1)

The config have to look like:

```
post_comp_extra = ["-threads", "2", "-flags", "+global_header", "-f", "tee", "-map", "0:v", "-map", "0:a"]
out_addr = "[f=flv]rtmp://example1.org/live/stream|[f=flv]rtmp://example2.org/live/stream"
```

I'm not totally sure if this works, maybe the mapping will fail.
