### ISSUE TITLE
Can't get ffplayout to work

### ISSUE THREAD

**Issue by mustafalani** [jb-alvarado/ffplayout#2]
Hi,

Thanks for the nice work.

I have followed your guide in ffplayout and ffplayout GUI but I can't get it to work.

Here is the output of the logs file:
[2018-11-03 21:04:13,146] [INFO]  open: /playlists/2018/11/2018-11-03.xml
[2018-11-03 21:04:13,147] [ERROR]  Playlist is not valid! /playlists/2018/11/2018-11-03.xml
[2018-11-03 21:04:13,147] [INFO]  play at "21:04:55":  ['-f', 'lavfi', '-i', 'color=s=1024x576:d=60', '-f', 'lavfi', '-i', 'anullsrc=r=44100', '-shortest']
[2018-11-03 21:04:13,149] [ERROR]  xml playlist is not long enough! total play time is: 3844.183333000001

Regards,
Mustafa

**Comment by jb-alvarado** [comment]
Hi Mustafa,
sorry for my late response! I was longer time in vacation...

Could it be, that your playlist is less long as your stating time? I see that your playlist is only one hour long, and you open ffplayout at 21:04:13. When your **day_start** is smaller, then of course there are no clips anymore to play.

What is your day_start value and your start time in your xml list?

**Comment by jb-alvarado** [comment]
In the ffplayout.conf file you can change this with: day_start.
And f you generate your playlist with the shell script example you can change the start time here:
```
# start time in seconds
listStart="21600"
```
You can set the time manually, but then you have to calculating the start time for every clip. Skipping and looping are not possible.

**Comment by mustafalani** [comment]
I have managed to set the start time manually like this:
`listStart=$2`

then the command to set the time manually would look like this
for start time @6:00 AM (21600= 06:00)
./gen_playlist_from_subfolders.sh /ADtvMedia/ 21600

Now how about making a short playlist like for one or two clips? I know it might not make sense, but is it possible?

**Comment by jb-alvarado** [comment]
> Now how about making a short playlist like for one or two clips? I know it might not make sense, but is it possible?

You could write your xml list by hand, or you use ffplayout-gui. When you setup this web-based gui right, you have on left your folder tree and from there you can drag&drop your clips to the new playlist/day.

The idea behind ffplayout is more something like [cinegy ](https://www.cinegy.com/). A solution for "tv stations"

We have for example a app with that we planing our days, ffplayout-gui we use for checking, controlling and if we have to change a clip quickly. And ffplayout streams then our stream to a rtmp server.

**Comment by mustafalani** [comment]
Totally agree. my issue now is when I add a clip or two to a new playlist I got this message:
Playtime from Playlist is to short!
Difference: -86222.535

Nothing been saved! I presume because of that message!

**Comment by jb-alvarado** [comment]
Ah yes, that is right - ok normally it should still play something, and when the playlist is done ffplayout should generate a black clip...

Anyway the problem is to, that ffplayout always want a 24 hours playlist. There is only a starting time, not an ending time.

**Comment by jb-alvarado** [comment]
> Playtime from Playlist is to short!
> Difference: -86222.535

You get this from ffplayout-gui? Sorry, I got confuse. Yes, that is right, at the moment it only save, when the playlist is long enough. For this you have to dive a bit deeper in the gui code, to remove this check.

**Comment by jb-alvarado** [comment]
From resources/js/custom.js you can remove line **539** and **540**.

I think after this you can save your playlist through ffplayout-gui

**Comment by mustafalani** [comment]
Very interesting.! what about having two (or more) playlists running simultaneously? will that need another ffplayout instance?

**Comment by jb-alvarado** [comment]
I have not test it, but I think it is possible. But every instance needs its own config and for the gui version it could become difficult. 
I would recommend to set this up in different containers, or vms.

**Comment by refriedfood** [comment]
Get script, any chance you'll make another version that works in command prompt / win OS?

**Comment by jb-alvarado** [comment]
> 
> 
> Get script, any chance you'll make another version that works in command prompt / win OS?

Please use for new questions, a new issue: https://github.com/jb-alvarado/ffplayout/issues/3
