### ISSUE TITLE
Playlist to short

### ISSUE THREAD

**Issue by jb-alvarado** [jb-alvarado/ffplayout#7]
In dev branch is a bug:
- the dummy clip don't needs a audio filter
- the playlist don't change to the next day.

**Comment by Angel54689** [comment]
Trying for last few hours. Master branch is not working for me. The Python script is stuck somewhere. I think I should try the dev branch.

**Comment by jb-alvarado** [comment]
Please open a new issue for that, with exact Description of the problem, the log file and the console output.
